### ISSUE TITLE
Unable to find template "components/paginate.twig" on update

### ISSUE THREAD

**Issue by VIS89** [RobiNN1/phpCacheAdmin#10]
Hello,
I've pulled latest changes and got error on Redis and Memcache:
"Unable to find template "components/paginate.twig" (looked into: /usr/local/share/phpcacheadmin/src/../templates). in /usr/local/share/phpcacheadmin/templates/partials/keys_table.twig at line: 64 "

Here's the log of pull:
emote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 167 (delta 113), reused 133 (delta 79), pack-reused 0
Receiving objects: 100% (167/167), 148.57 KiB | 4.95 MiB/s, done.
Resolving deltas: 100% (113/113), completed with 35 local objects.
From https://github.com/RobiNN1/phpCacheAdmin
   17342b8..38e08d7  master     -> origin/master
Updating 17342b8..38e08d7
Fast-forward
 .github/workflows/static-analysis.yml                                |  30 +++++++++++
 README.md                                                            |  24 +++------
 assets/css/src.css                                                   |   4 ++
 assets/css/styles.css                                                |   8 +--
 composer.json                                                        |   6 ++-
 index.php                                                            |  20 ++++++-
 phpstan.neon                                                         |   2 +-
 src/Admin.php                                                        |   4 +-
 src/Config.php                                                       |   2 +-
 src/Dashboards/DashboardInterface.php                                |   4 +-
 src/Dashboards/Memcached/MemcacheCompatibility/Memcache.php          |  12 +++--
 src/Dashboards/Memcached/MemcacheCompatibility/MemcacheInterface.php |   4 +-
 src/Dashboards/Memcached/MemcacheCompatibility/Memcached.php         |   4 +-
 src/Dashboards/Memcached/MemcachedDashboard.php                      |  20 +++----
 src/Dashboards/Memcached/MemcachedTrait.php                          |  90 +++++++++++++++----------------
 src/Dashboards/OPCache/OPCacheDashboard.php                          |   6 +--
 src/Dashboards/OPCache/OPCacheTrait.php                              |  23 ++++----
 src/Dashboards/Redis/GetValueTrait.php                               | 105 ------------------------------------
 src/Dashboards/Redis/RedisDashboard.php                              |  22 ++++----
 src/Dashboards/Redis/RedisFormTrait.php                              | 123 ------------------------------------------
 src/Dashboards/Redis/RedisTrait.php                                  | 208 ++++++++++++++++++++++++++++++----------------------------------------
 src/Dashboards/Redis/TypesTrait.php                                  | 240 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Dashboards/Server/ServerDashboard.php                            |   4 +-
 src/Helpers.php                                                      |  20 +++----
 src/Http.php                                                         |  10 ++--
 src/Paginator.php                                                    | 154 +++++++++++++++++++++++++++++++++++-----------------
 src/Template.php                                                     |   6 +--
 templates/components/input.twig                                      |   3 +-
 templates/components/{paginate.twig => paginator.twig}               |  19 +++----
 templates/dashboards/memcached/form.twig                             |  11 ++--
 templates/dashboards/opcache.twig                                    |   6 +--
 templates/dashboards/redis/form.twig                                 |   4 +-
 templates/partials/keys_table.twig                                   |   4 +-
 templates/partials/view_key.twig                                     |  28 ++++++----
 twig.phar                                                            | Bin 0 -> 671823 bytes
 35 files changed, 656 insertions(+), 574 deletions(-)
 create mode 100644 .github/workflows/static-analysis.yml
 delete mode 100644 src/Dashboards/Redis/GetValueTrait.php
 delete mode 100644 src/Dashboards/Redis/RedisFormTrait.php
 create mode 100644 src/Dashboards/Redis/TypesTrait.php
 rename templates/components/{paginate.twig => paginator.twig} (60%)
 create mode 100644 twig.phar

**Comment by RobiNN1** [comment]
Delete cache folder

**Comment by VIS89** [comment]
Thanks. All is good with the functionality, except the UI:
![image](https://user-images.githubusercontent.com/37146792/177539563-23810195-604b-4d33-a45c-3e4c599101d1.png)

**Comment by RobiNN1** [comment]
Yes, I noticed this as well when I installed magento for testing. 

But it's good that someone actually uses this tool and helps me find these little problems.

**Comment by VIS89** [comment]
We gonna use it for sure more, it looks really good and is easy to debug in case something happens and we want to check redis cache.

**Comment by RobiNN1** [comment]
Pagination is also now fixed.
