### ISSUE TITLE
never worked

### ISSUE THREAD

**Issue by tamimology** [RobiNN1/phpCacheAdmin#11]
I have Synology DS1513+ running the latest Docker v.20.10.3 and docker-compose v2.6.1. When I run the container as advised, I get this error for the PCA container:

`today at 21:44:38[Mon Jul 18 11:44:38.534724 2022] [:crit] [pid 7] (38)Function not implemented: AH00141: Could not initialize random number generator
today at 21:45:12Container stopped`

**Comment by RobiNN1** [comment]
https://stackoverflow.com/questions/72828247/how-to-fix-function-not-implemented-ah00141-could-not-initialize-random-numbe

According to that StackOverflow issue, your OS doesn't support the latest Apache HTTP server.
You can create own image with different http server.

So this is issue on your side.
