### ISSUE TITLE
FeatureRequest: Add APCu

### ISSUE THREAD

**Issue by B0bbyD0llar** [RobiNN1/phpCacheAdmin#12]
Hello.
It would be great if you could also manage APCu through this awesome tool.

**Comment by RobiNN1** [comment]
I already working on this, but it will be probably disabled by default (in config can enable/disable any dashboard). Since APCu is not that popular.

**Comment by RobiNN1** [comment]
Done https://github.com/RobiNN1/phpCacheAdmin/commit/02c81f01d419687877fb5487a4b8a05b33a35551

Add this line to your config.php https://github.com/RobiNN1/phpCacheAdmin/blob/0731081f3df38b31ffccd138d303cbb112389340/config.dist.php#L21
