### ISSUE TITLE
Docker release tags

### ISSUE THREAD

**Issue by cdubz** [RobiNN1/phpCacheAdmin#13]
Thanks for building this! I have created a [plugin](https://github.com/cdubz/lando-phpcacheadmin) implementing it for the Lando development environment and am pinning to the `latest` tag in Docker currently. Do you plan to add version tags to Docker eventually? I'm hoping to be able to pin the Lando plugin to specific release tags instead of `latest`.

**Comment by RobiNN1** [comment]
Yes I can. Doing these extra Docker releases is annoying, so I always just copy-paste the command to build and publish the docker image. That's why there is currently only 'latest' tag.

**Comment by cdubz** [comment]
Ah yeah -- Docker Hub doesn't have automated builds on non-paid plans anymore 😞 

Maybe the [Build and push Docker images](https://github.com/marketplace/actions/build-and-push-docker-images) GH Action could make this less annoying?

**Comment by RobiNN1** [comment]
I have re-released all versions with the correct tags. It should be fine now. https://hub.docker.com/r/robinn/phpcacheadmin/tags

I saw that ga action, will try later.
