### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by cfwl1111** [RobiNN1/phpCacheAdmin#17]
The UI is pretty good, but the page proportions are a little out of sync. In addition, I am deployed on a WAN for external access. Can I add login verification later?

**Comment by RobiNN1** [comment]
You mean panels with info? These panels are loaded via Ajax, so if the server is slower, you may see a loading icon. You can add multiple servers, and if one server is really slow if doesn't affect whole page loading.

In config file is example for simple login.

**Comment by cfwl1111** [comment]
The version number of the sidebar and the link to the project can be placed at the bottom, which should make the overall visual effect much better。
