### ISSUE TITLE
Display the current server resource usage

### ISSUE THREAD

**Issue by cfwl1111** [RobiNN1/phpCacheAdmin#20]
### Proposal

Can the server items in the sidebar increase the display of hardware resources, such as CPU and memory, similar to probes

### Motivation and context

Convenient to view the current server's resource usage

**Comment by RobiNN1** [comment]
This tool must work on any OS, and getting such information is different on all operating systems.

**Comment by RobiNN1** [comment]
Few years later, but i added in v2.6.0 cpu, ram and disk usage.
