### ISSUE TITLE
Undefined Array Key in /src/Dashboards/OPCache/OPCacheTrait.php:108

### ISSUE THREAD

**Issue by chrislp** [RobiNN1/phpCacheAdmin#26]
### What version of phpCacheAdmin are you using?

v1.6.2

### Extension or client and version

PHP OPCache extension v8.1.2-1ubuntu2.14

### PHP Version

8.1.2-1ubuntu2.14

### Operating System

Ubuntu 22.04.3 LTS

### Describe the issue

I got lots of warnings:
```
E_WARNING: Undefined array key "timestamp" in /var/www/cacheadm.dietz.digital/src/Dashboards/OPCache/OPCacheTrait.php on line 108
```

I ultimatively run into a fatal error - see below.

My workaround looks like this, it seems that the timestamp was renamed:
```php
                    $cached_scripts[] = [
                        'key'   => $script['full_path'],
                        'items' => [
                            'title'          => $full_path,
                            'number_hits'    => $script['hits'],
                            'bytes_memory'   => $script['memory_consumption'],
                            'time_last_used' => $script['last_used_timestamp'],
                            'time_created'   => (empty ($script['timestamp']) ) ? $script['last_used_timestamp'] : $script['timestamp'],
                        ],
                    ];
```

```
Fatal error: Uncaught TypeError: RobiNN\Pca\Format::time(): Argument #1 ($time) must be of type int, null given, called in /var/www/cacheadm.dietz.digital/tmp/1b/1b6e8da384b3268893718f80cd4f05a0.php on line 165 and defined in /var/www/cacheadm.dietz.digital/src/Format.php:88 Stack trace: #0 /var/www/cacheadm.dietz.digital/tmp/1b/1b6e8da384b3268893718f80cd4f05a0.php(165): RobiNN\Pca\Format::time() #1 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(394): __TwigTemplate_10079ab895f75fff0c7781e3d6ac5515->doDisplay() #2 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling() #3 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(379): Twig\Template->display() #4 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render() #5 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Extension/CoreExtension.php(1349): Twig\TemplateWrapper->render() #6 /var/www/cacheadm.dietz.digital/tmp/85/85f8b59c510ffbd1eb22dd8839b71cd0.php(72): twig_include() #7 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e42da5762703c4eb803012a289d27196->doDisplay() #8 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling() #9 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Template.php(379): Twig\Template->display() #10 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render() #11 /var/www/cacheadm.dietz.digital/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render() #12 /var/www/cacheadm.dietz.digital/src/Template.php(100): Twig\Environment->render() #13 /var/www/cacheadm.dietz.digital/src/Dashboards/OPCache/OPCacheTrait.php(131): RobiNN\Pca\Template->render() #14 /var/www/cacheadm.dietz.digital/src/Dashboards/OPCache/OPCacheDashboard.php(68): RobiNN\Pca\Dashboards\OPCache\OPCacheDashboard->mainDashboard() #15 /var/www/cacheadm.dietz.digital/index.php(87): RobiNN\Pca\Dashboards\OPCache\OPCacheDashboard->dashboard() #16 {main} thrown in /var/www/cacheadm.dietz.digital/src/Format.php on line 88
```

**Comment by RobiNN1** [comment]
You probably have `opcache.restrict_api` set because there are no changes in the api. `timestamp` still exists on PHP 8.2.

Also `last_used_timestamp` and `timestamp` is not the same value.

**Comment by chrislp** [comment]
Ahoj Róbert,

Thanks for pointing out, that the two timestamp values are actually different. 
`opcache.restrict_api` is empty on my server. Doe you have any other ideas what I might need to reconfigure?


| Directive                             | Local Value | Master Value |
|---------------------------------------|-------------|--------------|
| opcache.blacklist_filename            | no value    | no value     |
| opcache.consistency_checks            | 0           | 0            |
| opcache.dups_fix                      | Off         | Off          |
| opcache.enable                        | On          | On           |
| opcache.enable_cli                    | Off         | Off          |
| opcache.enable_file_override          | Off         | Off          |
| opcache.error_log                     | no value    | no value     |
| opcache.file_cache                    | no value    | no value     |
| opcache.file_cache_consistency_checks | On          | On           |
| opcache.file_cache_only               | Off         | Off          |
| opcache.file_update_protection        | 2           | 2            |
| opcache.force_restart_timeout         | 180         | 180          |
| opcache.huge_code_pages               | Off         | Off          |
| opcache.interned_strings_buffer       | 32          | 32           |
| opcache.jit                           | tracing     | tracing      |
| opcache.jit_bisect_limit              | 0           | 0            |
| opcache.jit_blacklist_root_trace      | 16          | 16           |
| opcache.jit_blacklist_side_trace      | 8           | 8            |
| opcache.jit_buffer_size               | 0           | 0            |
| opcache.jit_debug                     | 0           | 0            |
| opcache.jit_hot_func                  | 127         | 127          |
| opcache.jit_hot_loop                  | 64          | 64           |
| opcache.jit_hot_return                | 8           | 8            |
| opcache.jit_hot_side_exit             | 8           | 8            |
| opcache.jit_max_exit_counters         | 8192        | 8192         |
| opcache.jit_max_loop_unrolls          | 8           | 8            |
| opcache.jit_max_polymorphic_calls     | 2           | 2            |
| opcache.jit_max_recursive_calls       | 2           | 2            |
| opcache.jit_max_recursive_returns     | 2           | 2            |
| opcache.jit_max_root_traces           | 1024        | 1024         |
| opcache.jit_max_side_traces           | 128         | 128          |
| opcache.jit_prof_threshold            | 0.005       | 0.005        |
| opcache.lockfile_path                 | /tmp        | /tmp         |
| opcache.log_verbosity_level           | 1           | 1            |
| opcache.max_accelerated_files         | 1000000     | 1000000      |
| opcache.max_file_size                 | 0           | 0            |
| opcache.max_wasted_percentage         | 5           | 5            |
| opcache.memory_consumption            | 512         | 512          |
| opcache.opt_debug_level               | 0           | 0            |
| opcache.optimization_level            | 0x7FFEBFFF  | 0x7FFEBFFF   |
| opcache.preferred_memory_model        | no value    | no value     |
| opcache.preload                       | no value    | no value     |
| opcache.preload_user                  | no value    | no value     |
| opcache.protect_memory                | Off         | Off          |
| opcache.record_warnings               | Off         | Off          |
| opcache.restrict_api                  | no value    | no value     |
| opcache.revalidate_freq               | 5           | 5            |
| opcache.revalidate_path               | Off         | Off          |
| opcache.save_comments                 | On          | On           |
| opcache.use_cwd                       | On          | On           |
| opcache.validate_permission           | Off         | Off          |
| opcache.validate_root                 | Off         | Off          |
| opcache.validate_timestamps           | Off         | Off          |

**Comment by RobiNN1** [comment]
`opcache.validate_timestamps` is Off, that's the reason.


Just fix this line https://github.com/RobiNN1/phpCacheAdmin/commit/a60a6578d906dccf8a63f33aed36203d06dea1f5#diff-74799a95e19db50135ffce21e7dc3814c8485e02657e6bed7d6e92ba295ac0e1R108  it won't show the creation date, but it should be fine

**Comment by chrislp** [comment]
Thanks again. Since it's my server I just enabled `opcache.validate_timestamps` and it works perfectly!
