### ISSUE TITLE
Uncaught DivisionByZeroError in v2

### ISSUE THREAD

**Issue by dstockhofe** [RobiNN1/phpCacheAdmin#28]
### What version of phpCacheAdmin are you using?

2.0.0

### Cache system and version

Redis 7.0.15

### Extension or client and version

PHP Redis extension v6.0.2

### PHP Version

8.3.12

### Operating System

Ubuntu 24.04

### Describe the issue

I got a division by zero error on my fresh install

`Fatal error: Uncaught DivisionByZeroError: Division by zero in /src/Dashboards/Redis/RedisTrait.php:45 Stack trace: #0 /src/Dashboards/Redis/RedisDashboard.php(123): RobiNN\Pca\Dashboards\Redis\RedisDashboard->panels() #1 /index.php(83): RobiNN\Pca\Dashboards\Redis\RedisDashboard->dashboard() #2 {main} thrown in /src/Dashboards/Redis/RedisTrait.php on line 45`

So i changed line 45 to 
`$memory_usage = $max_memory > 0 ? round(($used_memory / $max_memory) * 100, 2) : 0;`
so i can use it.

**Comment by RobiNN1** [comment]
Fixed in https://github.com/RobiNN1/phpCacheAdmin/commit/9b63720128c244ec61865e611f09f27101ee9709

V2 is still w.i.p. so there are probably more errors like this.
