### ISSUE TITLE
New feature: Add ability to order columns

### ISSUE THREAD

**Issue by Lazir** [RobiNN1/phpCacheAdmin#29]
### Proposal

I need ablity to order columns (ASC or DESC) in memcached or APCu to find for example biggest cache by size. It is crucial to monitor which feature put too much data. Is it possible to make?

### Motivation and context

This feature is available in standard apcu.php panel. This would be great.

**Comment by RobiNN1** [comment]
Added in https://github.com/RobiNN1/phpCacheAdmin/commit/5ce0883f97dd6d32a922682f41ab79f97fb52001
