### ISSUE TITLE
Install without composer?

### ISSUE THREAD

**Issue by qcybb** [RobiNN1/phpCacheAdmin#5]
Is there any way to install this without using composer?

**Comment by RobiNN1** [comment]
Well, this project is supposed to be a development tool, and every developer should have a composer installed these days.

Anyway, after full testing, I'll create a release with pre-installed composer dependencies.

**Comment by RobiNN1** [comment]
Ok, I found a way to use it without composer.

I found that I can compile the composer package into a phar archive and autoload it. Fortunately, there is only one dependency - Twig template engine, so it's easy to do.

**Comment by qcybb** [comment]
Thank you, I really appreciate it!
